# Generated by Django 4.2.3 on 2023-11-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='category',
        ),
    ]
