# Generated by Django 4.2.3 on 2023-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_library_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.FileField(upload_to='products_videos'),
        ),
    ]
