# Generated by Django 4.2.3 on 2023-11-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='preview',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='video_url',
            new_name='video',
        ),
    ]
